### ISSUE TITLE
 undefined method `bytesize` again

### ISSUE THREAD

**Issue by amalagaura** [lostisland/faraday#414]
I read old error reports about undefined method bytesize where Net::HTTP is expecting a string but getting a hash. I am getting weird behavior in Ruby 2.0.

But to simplify, why is Faraday behaving like this?

This works in Ruby 1.9.3. It shows that Ruby 2.0 is supported, but this is really basic.

I am running

ruby 2.0.0p481 (2014-05-08 revision 45883) [x86_64-darwin13.1.0]
faraday 0.9.0
multipart-post 2.0.0

**This works**
`Faraday.new('https://my-site.com/').post('somewhere',{a: 1}).body`

**This Doesn't**

```
conn = Faraday.new('https://my-site.com/') do |conn|
                 conn.adapter Faraday.default_adapter 
            end
conn.post('somewhere',{a: 1}).body
```

`NoMethodError: undefined method bytesize' for {:a=>1}:Hash`
