### ISSUE TITLE
Bug when creating a new Faraday instance with `new(url: '')`

### ISSUE THREAD

**Issue by cimnine** [lostisland/faraday#694]
```ruby
Faraday.new(url: '')
```

Works in Faraday 0.11, doesn't work since Faraday 0.12:

```
NoMethodError: undefined method `each' for nil:NilClass
```

**Comment by iMacTia** [comment]
Hi @cimnine,

I think this is due to the new `find_proxy` feature we introduced in 0.12.
However, this only happens when you initialise faraday with an invalid url.

1. why would you do that?
2. Can you accomplish the same result passing nil (`Faraday.new(url: nil)`) or not passing it at all (`Faraday.new`)?

**Comment by cimnine** [comment]
If you put it that way, it now seems that the problem is not related to `url:`, but happens when any key of the options-hash is `nil`:

```ruby
Faraday.new #works
Faraday.new(url: nil) #breaks
Faraday.new(nil: nil) #breaks
Faraday.new(url: 'http://good', ssl: nil) #breaks
```

It happens to me because I usually pass something like `{ url: config.url, ssl: config.ssl }` to Faraday, which is `nil` (at least) during tests.

**Comment by iMacTia** [comment]
```ruby
Faraday::VERSION
=> 0.12.1

conn = Faraday.new(url: nil)
=> #<Faraday::Connection:0x007f834683cd45 ...>

conn.get('https://test.com')
=> #<Faraday::Response:0x007f834807b2 ...>
```

The above works for me. Are you sure you're on version 0.12.1?

**Comment by cimnine** [comment]
I guess `Faraday.new(url: nil)` breaks for me, because I have defined some `default_options`. It does not break, if I run it in irb/pry without any prior configuration.

When I do it in pry, it works. But I can reproduce the error anyway:

```
[1] pry(main)> require 'faraday'
=> true
[2] pry(main)> Faraday.new(url: 'http://good', ssl: nil)
NoMethodError: undefined method `each' for nil:NilClass
from /usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.12.1/lib/faraday/options.rb:49:in `merge!'
```

**Comment by iMacTia** [comment]
I think the overall assumption is that if you provide a value for those properties then the value should be a valid one. The fact that it was working in the past doesn't mean that it was suppose to, we were simply lucky with that.
In fact, there's no automated test that checks for nil values to be provided, so that's not something we want to support.
I understand it's not ideal to have something working that breaks with an update, but in this case I see it more like an "unwanted" feature. It shouldn't have worked from the beginning.
Happy to provide help in fixing the issue though if you have any issue.

**Comment by neckhair** [comment]
My assumption is that if the Hash accepts a key and the value is `nil` it sets the option to `nil` or ignores it. Because this behaviour makes configurations a bit easier. 
As this is quite a central config it might make sense to check the value and raise an `ArgumentError` or something similar. This would at least explain a wrong doing by the user of the API.
But I understand your point @iMacTia. It's up to you.

**Comment by iMacTia** [comment]
Ok, when we added `merge!` to options we tried to mimic the behaviour of ActiveSupport's `deep_merge`. If I try to do something similar with that, I get the following:

```ruby
h1 = { a: 100, b: 200, c: { c1: 100 } }
h2 = { b: 250, c: nil}

h1.deep_merge h2
# => {:a=>100, :b=>250, :c=>nil}
```

So according to that, the expected behaviour would be to override the default with nil when explicitly passing the argument. That makes sense to me as well as it provides a simple way to override the default value when needed and it's in line with one of the most used library.
@cimnine would that be ok for your case as well?

**Comment by cimnine** [comment]
Yes, that would be great.

**Comment by iMacTia** [comment]
That's great.
It should be a relatively straightforward change to the `merge!` method.
I'll try to find some time to fix it before the next minor release (0.12.2).
Thanks for reporting this and following up guys 😃

**Comment by neckhair** [comment]
Cool, thanks!

**Comment by iMacTia** [comment]
@cimnine @neckhair 
Sorry for the delay. Today I had some time to look into this.
Unfortunately, the `ActiveSupport#deep_merge`-like behaviour is not possible in this case because when it comes to `Options` all keys are always present, with value nil. Thus the `a.merge(b)` would result in all keys in `a` missing in `b` being deleted.
However, I was able to fix the "NoMethodError: undefined method 'each' for nil:NilClass" issue, as the `merge` method will now avoid trying to merge sub-options when the value is nil.

I would appreciate your feedback before merging the PR. Thanks 😄

**Comment by neckhair** [comment]
@iMacTia Thanks for doing this! We tested it and it seems to work. So, good to merge.
