### ISSUE TITLE
undefined method `each' for String

### ISSUE THREAD

**Issue by morgoth** [lostisland/faraday#684]
After update to 0.12.0.1, I get exception on retrying simple JSON request
```
     NoMethodError:
       undefined method `each' for #<String:0x005645b5eaa488>
```
It happens here https://github.com/lostisland/faraday/blob/a5f027e1ce70663563cfd4e68396443701ef1041/lib/faraday/request/retry.rb#L155

In this place `env` is just a string.
Looks like introduced by https://github.com/lostisland/faraday/pull/669 /cc @hawknewton

**Comment by iMacTia** [comment]
Hi @morgoth, thanks for reporting this.
Indeed I see the issue here, the `rewind_files` method is missing a check on the type of the body.
I presume the issue in your case is that the retry middleware is down on the middlewares stack, you should be able to fix this moving it to the top (or anyway before the encoding middleware).
However, this is something that should be addressed anyway checking the type of the body to be an `Hash`. I'll work on a fix for the next release 👍

**Comment by morgoth** [comment]
Thanks, not sure what's the encoding middleware. For me it looks like:
```ruby
Faraday.new(url: url) do |faraday|
  faraday.request(:retry, max: 3,
                  interval: 1,
                  methods: [:delete, :get, :head, :options, :put, :post],
                  exceptions: [
                    Faraday::Error::TimeoutError,
                    Faraday::ConnectionFailed,
                    Faraday::ClientError,
                    Errno::ETIMEDOUT,
                    "Timeout::Error"
                  ])
  faraday.adapter :excon
  faraday.use Faraday::Response::RaiseError
end
```
Moving `faraday.use Faraday::Response::RaiseError` to top workarounds the problem.

**Comment by iMacTia** [comment]
That makes sense, the adapter should always be the last one in the stack and the `RaiseError` was apparently interfering in that position.
Anyway, I pushed a fix on the master branch that should have fixed this issue.
You're free to set back the stack and test with the master branch of the gem if you want
